name: Update GitHub Pages with URLs

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository to access files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set current timestamp in CST timezone
      - name: Set last updated timestamp in CST timezone
        id: timestamp
        run: |
          export TZ="America/Chicago"
          echo "LAST_UPDATED=$(date +"%B %d, %Y at %I:%M %p %Z")" >> $GITHUB_ENV

      # Fetch webpage content and build HTML file
      - name: Generate HTML with Links
        run: |
          # Define target URL
          URL="https://nirbytes.com/post/1000-proxies-for-school-chromebook-2024"
          LAST_UPDATED="${{ env.LAST_UPDATED }}"
          
          # Fetch webpage content
          RESPONSE=$(curl -s "$URL")

          # Build HTML content
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Generated Links</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      background-color: #121212;
                      color: #f5f5f5;
                      line-height: 1.6;
                      margin: 0;
                      padding: 20px;
                  }
                  .container {
                      max-width: 800px;
                      margin: auto;
                      padding: 20px;
                      background: #1f1f1f;
                      border-radius: 10px;
                      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.5);
                  }
                  a {
                      color: #66ccff;
                      text-decoration: none;
                  }
                  a:hover {
                      color: #ff9900;
                  }
                  .button {
                      display: inline-block;
                      padding: 10px 20px;
                      background-color: #66ccff;
                      color: white;
                      border-radius: 5px;
                      text-decoration: none;
                      margin-top: 10px;
                  }
                  .button:hover {
                      background-color: #ff9900;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Auto-Generated Links</h1>
                  <p><strong>Last Updated:</strong> $LAST_UPDATED</p>
                  <p>
                      <button class="button" id="fetchContentButton">Open Check.html</button>
                  </p>
              </div>
              <script>
                  document.getElementById('fetchContentButton').addEventListener('click', () => {
                      const htmlContentUrl = 'https://raw.githubusercontent.com/unblock-eve/unblock-eve.github.io/refs/heads/main/check.html';
                      fetch(htmlContentUrl)
                          .then(response => response.text())
                          .then(content => {
                              const newTab = window.open();
                              newTab.document.open();
                              newTab.document.write(content);
                              newTab.document.close();
                          })
                          .catch(err => alert('Failed to fetch the content!'));
                  });
              </script>
          </body>
          </html>
          EOF

      # Commit and push changes to the repository
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-update HTML with fetch button"
          git push
