name: Update GitHub Pages with URLs
on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository to access files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set current timestamp in CST timezone
      - name: Set last updated timestamp in CST timezone
        id: timestamp
        run: |
          export TZ="America/Chicago"
          echo "LAST_UPDATED=$(date +"%B %d, %Y at %I:%M %p %Z")" >> $GITHUB_ENV

      # Generate HTML file with embedded "check.html" content
      - name: Generate HTML file with embedded local content
        run: |
          LAST_UPDATED="${{ env.LAST_UPDATED }}"
          
          # Simulated content for check.html
          CHECK_HTML_CONTENT=$(cat <<'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Link Checker / RMA</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #121212;
            color: #e0e0e0;
            margin: 0;
            padding: 0;
            line-height: 1.6;
        }
        header {
            background-color: #1f1f1f;
            padding: 20px 0;
            text-align: center;
            color: #ffffff;
            font-size: 1.8rem;
            font-weight: bold;
            border-bottom: 1px solid #333;
        }
        .container {
            max-width: 800px;
            margin: 30px auto;
            padding: 20px;
            background-color: #1a1a1a;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
        }
        .title {
            font-size: 1.4rem;
            margin: 20px 0 10px;
            color: #00bcd4;
            border-bottom: 1px solid #333;
            padding-bottom: 5px;
        }
        .result {
            margin: 10px 0;
            padding: 12px;
            border-radius: 5px;
            border: 1px solid #333;
            transition: background-color 0.3s ease, border-color 0.3s ease;
        }
        .success {
            background-color: #1d2b1d;
            border-color: #4caf50;
            color: #4caf50;
        }
        .failure {
            background-color: #2b1d1d;
            border-color: #f44336;
            color: #f44336;
        }
        a {
            color: #00bcd4;
            text-decoration: none;
            font-weight: bold;
        }
        a:hover {
            text-decoration: underline;
        }
        footer {
            text-align: center;
            padding: 15px 0;
            font-size: 0.9rem;
            color: #888;
            background-color: #1f1f1f;
            border-top: 1px solid #333;
        }
    </style>
</head>
<body>
    <header>
        Link Checker
    </header>
    <div class="container">
        <div id="results"></div>
    </div>
    <footer>
        &copy; 2025 | Minimalist Black Theme | Powered by GitHub Actions
    </footer>
    <script>
        fetch('https://raw.githubusercontent.com/unblock-eve/unblock-eve.github.io/refs/heads/main/links.json')
            .then(response => {
                if (!response.ok) {
                    throw new Error(`Failed to load links.json: ${response.statusText}`);
                }
                return response.json();
            })
            .then(data => {
                const resultsDiv = document.getElementById('results');
                for (const [title, links] of Object.entries(data)) {
                    if (title === "Table of Contents") continue;
                    const validLinks = links.filter(link => !link.includes('youtube.com'));
                    if (validLinks.length === 0) continue;
                    const titleDiv = document.createElement('div');
                    titleDiv.className = 'title';
                    titleDiv.textContent = `Category: ${title}`;
                    resultsDiv.appendChild(titleDiv);
                    validLinks.forEach(link => {
                        const resultDiv = document.createElement('div');
                        resultDiv.className = 'result';
                        if (link.includes('vercel.app')) {
                            resultDiv.textContent = `${link} - ❌ Invalid (vercel.app domain)`;
                            resultDiv.classList.add('failure');
                            resultsDiv.appendChild(resultDiv);
                            return;
                        }
                        resultDiv.textContent = `Checking: ${link}`;
                        resultsDiv.appendChild(resultDiv);
                        fetch(link, { mode: 'no-cors' })
                            .then(() => {
                                resultDiv.textContent = '';
                                const linkElement = document.createElement('a');
                                linkElement.href = link;
                                linkElement.target = "_blank";
                                linkElement.textContent = link;
                                resultDiv.appendChild(linkElement);
                                resultDiv.classList.add('success');
                            })
                            .catch(() => {
                                resultDiv.textContent = `${link} - ❌ Fail`;
                                resultDiv.classList.add('failure');
                            });
                    });
                }
            })
            .catch(error => {
                const resultsDiv = document.getElementById('results');
                resultsDiv.textContent = `Error: ${error.message}`;
            });
    </script>
</body>
</html>
          EOF
          )

          # Main index.html with embedded local content
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Extracted Proxy Links</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      background-color: #121212;
                      color: #f5f5f5;
                      margin: 0;
                      padding: 0;
                  }
                  .container {
                      width: 80%;
                      margin: 30px auto;
                      padding: 20px;
                      background-color: #1f1f1f;
                      border-radius: 10px;
                  }
                  .toggle-btn {
                      display: inline-block;
                      padding: 10px 20px;
                      background-color: #66ccff;
                      color: white;
                      border-radius: 5px;
                      text-decoration: none;
                      cursor: pointer;
                  }
                  .toggle-btn:hover {
                      background-color: #ff9900;
                  }
                  .hidden {
                      display: none;
                  }
              </style>
              <script>
                  function toggleCheckHtml() {
                      const checkHtmlDiv = document.getElementById('check-html-content');
                      checkHtmlDiv.classList.toggle('hidden');
                  }
              </script>
          </head>
          <body>
              <div class="container">
                  <h1>Extracted Proxy Links</h1>
                  <p><strong>Last Updated:</strong> $LAST_UPDATED</p>
                  <button class="toggle-btn" onclick="toggleCheckHtml()">Open Link Checker Tool</button>
                  <div id="check-html-content" class="hidden">
                      $CHECK_HTML_CONTENT
                  </div>
              </div>
          </body>
          </html>
          EOF

      # Commit and push changes to the repository
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Embed local link checker tool in the main HTML"
          git push
