name: Update GitHub Pages with URLs

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

jobs:
  update-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0      # full history to detect changes

      - name: Generate timestamp
        id: timestamp
        run: |
          # Use ISO format for consistency
          LAST_UPDATED=$(date -u +"%B %d, %Y at %I:%M %p UTC")
          echo "LAST_UPDATED=${LAST_UPDATED}" >> $GITHUB_ENV

      - name: Render index.html from template
        run: |
          envsubst '${LAST_UPDATED}' < index.template.html > index.html

      - name: Check for changes
        run: |
          if git diff --exit-code --quiet; then
            echo "No changes detected; skipping commit."
            exit 0
          fi

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "chore: update last-updated to ${{ env.LAST_UPDATED }}"
          git push
