name: Update GitHub Pages with URLs
on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository to access files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set current timestamp in CST timezone
      - name: Set last updated timestamp in CST timezone
        id: timestamp
        run: |
          export TZ="America/Chicago"
          echo "LAST_UPDATED=$(date +"%B %d, %Y at %I:%M %p %Z")" >> $GITHUB_ENV

      # Generate HTML file with embedded "check.html" content
      - name: Generate HTML file with embedded local content
        run: |
          LAST_UPDATED="${{ env.LAST_UPDATED }}"
          
          # Simulated content for check.html
          CHECK_HTML_CONTENT=$(cat <<'EOF'
          <h2>Link Checker Tool</h2>
          <p>This is a simulated version of the local tool.</p>
          <ul>
              <li>Test Link 1: <a href="https://example.com" target="_blank">https://example.com</a></li>
              <li>Test Link 2: <a href="https://test.com" target="_blank">https://test.com</a></li>
          </ul>
          EOF
          )

          # Main index.html with embedded local content
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Extracted Proxy Links</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      background-color: #121212;
                      color: #f5f5f5;
                      margin: 0;
                      padding: 0;
                  }
                  .container {
                      width: 80%;
                      margin: 30px auto;
                      padding: 20px;
                      background-color: #1f1f1f;
                      border-radius: 10px;
                  }
                  .toggle-btn {
                      display: inline-block;
                      padding: 10px 20px;
                      background-color: #66ccff;
                      color: white;
                      border-radius: 5px;
                      text-decoration: none;
                      cursor: pointer;
                  }
                  .toggle-btn:hover {
                      background-color: #ff9900;
                  }
                  .hidden {
                      display: none;
                  }
              </style>
              <script>
                  function toggleCheckHtml() {
                      const checkHtmlDiv = document.getElementById('check-html-content');
                      checkHtmlDiv.classList.toggle('hidden');
                  }
              </script>
          </head>
          <body>
              <div class="container">
                  <h1>Extracted Proxy Links</h1>
                  <p><strong>Last Updated:</strong> $LAST_UPDATED</p>
                  <button class="toggle-btn" onclick="toggleCheckHtml()">Open Link Checker Tool</button>
                  <div id="check-html-content" class="hidden">
                      $CHECK_HTML_CONTENT
                  </div>
              </div>
          </body>
          </html>
          EOF

      # Commit and push changes to the repository
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Embed local link checker tool in the main HTML"
          git push
