name: Update GitHub Pages with URLs
on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:

jobs:
  update-pages:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository to access files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set current timestamp in CST timezone
      - name: Set last updated timestamp in CST timezone
        id: timestamp
        run: |
          export TZ="America/Chicago"
          echo "LAST_UPDATED=$(date +"%B %d, %Y at %I:%M %p %Z")" >> $GITHUB_ENV

      # Fetch and parse webpage into HTML and JSON
      - name: Fetch and parse webpage into HTML and JSON
        run: |
          # Define last updated timestamp
          LAST_UPDATED="${{ env.LAST_UPDATED }}"
          
          # Generate HTML content with the corrected <a> tag
          cat <<EOF > index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Extracted Proxy Links</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      background-color: #121212;
                      color: #f5f5f5;
                      margin: 0;
                      padding: 0;
                      line-height: 1.6;
                  }
                  .container {
                      width: 80%;
                      margin: 30px auto;
                      padding: 20px;
                      background-color: #1f1f1f;
                      border-radius: 10px;
                  }
                  .download-btn {
                      display: inline-block;
                      padding: 10px 20px;
                      background-color: #66ccff;
                      color: white;
                      border-radius: 5px;
                      text-decoration: none;
                  }
                  .download-btn:hover {
                      background-color: #ff9900;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Extracted Proxy Links</h1>
                  <p><strong>Last Updated:</strong> $LAST_UPDATED</p>
                  <a href="check.html" class="download-btn" target="_blank">
                      Open link checker
                  </a>
              </div>
          </body>
          </html>
          EOF

      # Commit and push changes to the repository
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update HTML to open the link checker locally"
          git push
